[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true
[[redirects]]
  from = "/growth"
  to = "/growth.html"
  status = 200
  force = true
[[redirects]]
  from = "/signin"
  to = "/signin.html"
  status = 200
  force = true
[[redirects]]
  from = "/signup"
  to = "/signup.html"
  status = 200
  force = true